### Get all books
GET http://localhost:5050/books
Accept: application/json


### Get book by id
GET http://localhost:5050/books/65cfab18aca07b286988e13d
Accept: application/json


### Create a book
POST http://localhost:5050/books
Content-Type: application/json

{
  "title": "The Great Gatsby",
  "description": "The Great Gatsby is a novel by American author F. Scott Fitzgerald. The book was published in 1925.",
  "author": "F. Scott Fitzgerald",
  "publishYear": 1925
}


### Update a book
PUT http://localhost:5050/books/65cfab54334445fc48b1776e
Content-Type: application/json

{
  "title": "The Great Gatsby",
  "author": "F. Scott Fitzgerald",
  "publishYear": 2000
}


### Delete a book
DELETE http://localhost:5050/books/65cfa5aa7ebfad7bd2585d6f


